// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1_7Ni2tTPloZLQ_g1tvucNIfpWeFNQY4',
    appId: '1:277557539813:web:a93b387f32166de2f0750c',
    messagingSenderId: '277557539813',
    projectId: 'eventos-e7a2c',
    authDomain: 'eventos-e7a2c.firebaseapp.com',
    storageBucket: 'eventos-e7a2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoEn3tlHuSFHh0obDXAy6zLnXDAqaDzYg',
    appId: '1:277557539813:android:3b8274ccb000566ff0750c',
    messagingSenderId: '277557539813',
    projectId: 'eventos-e7a2c',
    storageBucket: 'eventos-e7a2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5bbtzVCRBueWE-YGTQ6BxXaYxOr5_0M',
    appId: '1:277557539813:ios:85e272f79c7a6b0ef0750c',
    messagingSenderId: '277557539813',
    projectId: 'eventos-e7a2c',
    storageBucket: 'eventos-e7a2c.firebasestorage.app',
    iosBundleId: 'com.example.eventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX5bbtzVCRBueWE-YGTQ6BxXaYxOr5_0M',
    appId: '1:277557539813:ios:85e272f79c7a6b0ef0750c',
    messagingSenderId: '277557539813',
    projectId: 'eventos-e7a2c',
    storageBucket: 'eventos-e7a2c.firebasestorage.app',
    iosBundleId: 'com.example.eventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1_7Ni2tTPloZLQ_g1tvucNIfpWeFNQY4',
    appId: '1:277557539813:web:0daf608018988691f0750c',
    messagingSenderId: '277557539813',
    projectId: 'eventos-e7a2c',
    authDomain: 'eventos-e7a2c.firebaseapp.com',
    storageBucket: 'eventos-e7a2c.firebasestorage.app',
  );
}
